default['chef_backend_version'] = '2.0.1'
default['chef_frontend_version'] = '12.19.31'
default['auth_cidr_addresses'] = '0.0.0.0/0'
default['chef_cluster_master'] = '10.0.1.147'
default['chef_config_bucket'] = 'foghorn-darnold-s3infra'
default['chef_config_path'] = 'chef-build/testing'