default['chef_backend_version'] = '${chef_backend_version}'
default['chef_frontend_version'] = '${chef_frontend_version}'
default['auth_cidr_addresses'] = '${chef_auth_cidr_addresses}'
default['chef_cluster_master'] = '${chef_cluster_master}'
default['chef_config_bucket'] = '${chef_config_bucket}'
default['chef_config_path'] = '${chef_config_path}'